# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fcd5b84b41a1549331c9664b3d565dfbdbbb080cfdefd842d87a5624ef14f84425a894174cd2936509fd0e91307b8dbd277871f1326cb0f2483f0eef53f605c8

test:
  secret_key_base: 0c3aef710a60455250e9b2821ecd917407dbf649beb1b05fd18d2d6d3acd0747d5d302a2dd3bc1a1210cf22dec3dc7dc40361db9e89c4b534b0ed4d50d690168

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
